# Generated by Django 4.2 on 2026-06-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop Conducted'), ('Attended Event', 'Attended Event')], default='Workshop', max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
