# Generated by Django 4.2 on 2026-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Workshop', 'Workshop Conducted'), ('Attended Event', 'Attended Event'), ('Inauguration', 'Inauguration Ceremony'), ('Conference', 'Conference Presentation'), ('Fest', 'Fest'), ('Special Day', 'Special Day Celebration')], default='Workshop', max_length=50),
        ),
    ]
